### PR TITLE
Changed names for environment types agroforestry and aquaculture 

### PR DESCRIPTION
**Pull request by nedhorning**
Changed environment types agroforestry and aquaculture to include the term system in the name

### CODE REVIEW

**Review by aaronc — COMMENTED** [review]
Is the nomenclature "system" or "site" better? These could also be Agroforestry Site, etc

**Comment by nedhorning** [comment]
I prefer "system," but I"'m open to changing it

**Comment by aaronc** [comment]
I'm fine to stick with system too

**Review by beccaRND — APPROVED** [review]
approved

**Review by clevinson — APPROVED** [review]

**Pull request merged**
